### ISSUE TITLE
据我所知这貌似是个适用于Win而不是Linux

### ISSUE THREAD

**Issue by Lianshang233** [opq-osc/OPQBot-Native#4]
OPQ大部分用于是基于Linux进行运行的，希望可以在Linux系里运行此程序
[机器翻译，可能有一些不准确]

**Comment by Hellobaka** [comment]
限于酷q插件，这个程序的运行平台只能是win-x86。不过你依旧可以使用`wine`来做兼容层，这个方法我之前尝试过能够正常运行并且加载插件的
